import { Inter } from 'next/font/google'
import Navbar from './navbar'
import Footer from './footer'
import StickyBox from './Stickybox'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Hello World',
//   description: 'Generated by Yasumin',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <div className="row">
        <StickyBox offsetTop={10} offsetBottom={10} bottom style={{ alignSelf: "flex-end" }}>
          <div className="">
            <button className="" >Sidebar</button>
          </div>
        </StickyBox>
        <main className={inter.className}>{children}</main>
      </div>
      <Footer />
    </>
  )
}
